name: aladhan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  adhan: ^2.0.0+1
  animate_do: ^3.3.3
  awesome_notifications: ^0.9.2
  circular_countdown_timer: ^0.2.3
  equatable: ^2.0.5
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_islamic_icons: ^1.0.2
  flutter_qiblah: ^2.2.1
  flutter_spinkit: ^5.2.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  group_button: ^5.3.4
  overlay_support: ^2.1.0
  shimmer: ^3.0.0
  supabase_flutter: ^2.3.4
  unicons: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - .env
  - assets/
  
